server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8

# mysql
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #MySQL
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/invoice?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss


mybatis-plus:
  mapperLocations: classpath:mapper/**/*.xml
  #configuration:
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #??sql??

# 自定义变量
ip: 'localhost'
url: 'http://127.0.0.1:8082/'